# Generated by Django 2.2.6 on 2020-03-04 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=100)),
                ('specialty', models.CharField(max_length=200)),
                ('dept', models.CharField(max_length=200)),
                ('date_hire', models.DateTimeField(verbose_name='date hired')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('dob', models.DateTimeField(verbose_name='date of birth')),
                ('sex', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField(help_text='date of visit.')),
                ('description', models.CharField(default=None, help_text='Describe reason for patient visit.', max_length=500)),
                ('prescription', models.CharField(default=None, help_text='Input any medication prescribed to patient by doctor.', max_length=500)),
                ('follow_up_care', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date and time this page was created. Automatically generated when the model saves.')),
                ('modified', models.DateTimeField(auto_now=True, help_text='The date and time this page was updated. Automatically generated when the model updates.')),
                ('doctor', models.ForeignKey(help_text='The doctor that entered this record.', on_delete=django.db.models.deletion.PROTECT, to='records.Doctor')),
                ('patient', models.ForeignKey(help_text='The patient associated with this record', on_delete=django.db.models.deletion.PROTECT, to='records.Patient')),
            ],
        ),
    ]
